title: Morups Tech Blog
email: chrmorup@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A technical learning journal documenting insights and experiences in software engineering,
  cloud architecture, and security. Join me in exploring complex technical concepts through
  detailed blog posts aimed at deepening understanding and sharing knowledge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChristianMorup
github_username:  ChristianMorup

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
